### ISSUE TITLE
L'affichage des Timestamps des derniers changement sur un résumé ne fonctionne plus

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#10]

**Comment by Nvince76** [comment]
A supprimer si faux bug
Mais en cochant ''Affiché la durée depuis le dernier changement'' le timestamp ne s'affiche plus

**Comment by fobsoft** [comment]
J'ai fait un test en désélectionnant l'option et la durée c'est effacé, ensuite resélectionné l'option et la durée c'est affiché.

Si tu pointe la  sourie sur l'icone, il y a bien des dates de valeur et collecte ?
Quel est le sous-type de la commande ?
Et quel widget est configuré sur cette commande ?

**Comment by Nvince76** [comment]
Ca refonctionne de mon coté...
Mais avait bien fait plusieurs tests non opérationnels

**Comment by fobsoft** [comment]
Je crois que c'était peut être une question de cash. Le browser lui même peut conduire à ce genre de problème et la config dans jeedom sous Configuration / Cache.
