### ISSUE TITLE
Generic Type Manager - Problème lors de configuration de variable text

### ISSUE THREAD

**Issue by fobsoft** [fobsoft/jeedom-plugins-documentation#14]

**Comment by fobsoft** [comment]
Correction soumise a la prochaine version

**Comment by Nvince76** [comment]
;) attendue avec impatience

**Comment by Nvince76** [comment]
J'ai essayé par un événement et par la commande de passage de variable, aucun des deux n'a réalisé l'écriture 

![image](https://user-images.githubusercontent.com/44101114/174668133-557e33e3-95bd-4c12-a84e-71e89ca9602c.png)

![image](https://user-images.githubusercontent.com/44101114/174668322-4241adae-3331-4a5a-b192-68ed1d6b0d2f.png)

![image](https://user-images.githubusercontent.com/44101114/174668412-16dcc328-a2c8-409d-936e-2fd7566ea68a.png)

Aucun changement sur la variable 'NOTIFICATION - Texte' initialement fixée à "Test Alexa"

![image](https://user-images.githubusercontent.com/44101114/174668626-3257979b-9272-4d7d-ba0f-48c5104c2d2e.png)

**Comment by fobsoft** [comment]
Ok, je vais re-tester cela, après toute les modifs effectuées il se peut
que j'ai perdu quelque chose. Peux-tu me faire un screen shoot de la config
de variable. Normalement cela aurait du fonctionner avec la deuxième
tentative.

Le lun. 20 juin 2022, à 15 h 42, Nvince76 ***@***.***> a
écrit :

**Comment by Nvince76** [comment]
bon en faisant d'autre test, le problème peut être commun avec la nouvelle issue que j'ai ouvert : 
MAJ JUN20 : les commandes ne sont plus fonctionnelles depuis le dashboard (le retour d'info fonctionne)

J'ai retesté le résumé en activant/désactivant le virtuel 'NOTIFICATION - Activation' mais pas de changement d'atat observé, les commandes ne passent pas.

![image](https://user-images.githubusercontent.com/44101114/174669580-3a8ea2f1-700e-4807-9a59-feb0ec77c30f.png)

**Comment by fobsoft** [comment]
Surement lié au refactoring pour avoir plusieurs generic de même type, ne
perd pas ton temps, je tente d'en trouver un peu ce soir et corrige ca

Le lun. 20 juin 2022, à 15 h 52, Nvince76 ***@***.***> a
écrit :

**Comment by Nvince76** [comment]
![image](https://user-images.githubusercontent.com/44101114/174670050-d3aac727-c236-4af4-af23-c928bfaf3cba.png)

encore merci pour tout le temps que tu y passes.
pense quand même à profiter un peu de tes journées ;)

**Comment by fobsoft** [comment]
De mon coter je me sens un peu de tous les bobos sur lesquelles tu tombe...
on va stabilisé tous ca avant de rajouter quelwue chose.

**Comment by Nvince76** [comment]
j'ai fait pas mal de développements par le passé, je sais ce que c'est.
Et, en plus, un peu peu chiant d'avoir quelqu'un qui pousse à la roue (si tu connais l'expression), 
mais ne t'inquiète pas, prends ton temps, pas d'urgence, l'objectif est que tu arrives à un plugin au top
moi je ne suis que le beta testeur ;)
pour l'instant je ne vois qu'un plugin qui s'améliore jour après jour

**Comment by fobsoft** [comment]
Le fait que tu pousse a la roue sa me motive plus qu'autre chose. Je sais
de mon côté que lorsque notre petite famille nous permet de mettre du temps
la dessus que c'est plaisant d'avancer et de ne pas trop tourner en rond.
Mais ceci dit, je tiens à te dire que tes efforts sont très apprécier.

**Comment by Nvince76** [comment]
la résolution du problème à bel et bien été perturbé par le problème :
MAJ JUN20 : les commandes ne sont plus fonctionnelles depuis le dashboard (le retour d'info fonctionne)

La variable texte est à présent bien passée 

Super!
tu peux clore

**Comment by fobsoft** [comment]
Si tu fait "Verifier les mise a jour" Tu devrais l'avoir, je viens de
forcer la nouvelle version. Attention, pour que cela fonction tu dois
resauvegarder ton GTM

Le sam. 18 juin 2022, à 14 h 23, Nvince76 ***@***.***> a
écrit :
