### ISSUE TITLE
Generic Type Manager - La sélection d'un mode sur la tuile du dashboard ne sélectionne pas la bonne 

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#15]
La sélection d'un mode sur la tuile du dashboard en cliquant sur le bouton correspondant n'active pas le mode correspondant mais un autre

**Comment by Nvince76** [comment]
sélectionne un autre ou aucun

**Comment by fobsoft** [comment]
Étrange, je ne me rappel pas avoir toucher cette section, je regarde ce
soir si j'ai du temps sinon demain matin

**Comment by fobsoft** [comment]
Re-test a la prochaine version, si toujours pas fonctionnel, transmet moi le log

**Comment by Nvince76** [comment]
ok

je vais pousser la version de ce jour et te redis

**Comment by Nvince76** [comment]
Parfait cela refonctionne
Je clos l'issue
