### ISSUE TITLE
AMELIORATION : Création d'une commande sans type générique

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#16]
Il est possible de faire un résumé INFO sans type générique, en sélectionnant aucune.
Il n'y a pas cette possibilité pour une commande sans type générique.

Exemple : je souhaiterai avoir un résumé sur une commande VOLUME (google mini, Free Delta,  Alexa, ...) mais je n'ai pas trouvé de méthode

![image](https://user-images.githubusercontent.com/44101114/174498909-17fb29f9-00b0-439e-87ee-a3e2dab07703.png)

**Comment by Nvince76** [comment]
A noter, une fois l'ensemble de la gestion terminée, la tuile du dashboard pourra servir de panneau de contrôle pour la pièce concernée...

Les modes permettront de mettre la pièce dans l'ambiance souhaitée (manuelle ou automatique (exemple en mode nuit), 
Les résumés INFO (en vert) permettront de se repérer sur les événements clés gérant toutes les logiques,
Le résumés COMMANDE (en Bleu) donne une indication sur le statut des commandes actuelles et permettent de donner la mains

**Comment by fobsoft** [comment]
Si je permet cela, le systeme va ramasser toute les commandes qui n'ont pas de type générique et je voudrait éviter ceci pour ne pas alourdir le flow. Cependant, je pourrais facilement ajouter une fonction au advancedScenario qui permettrais l'ajout de type générique, il suffirait alors de faire un déclanchement au #start# du système.

**Comment by Nvince76** [comment]
c'est pas faux.
Une commande volume sera t-elle rajoutée? Je serais surpris que cette dernière ne soit pas générique

**Comment by Nvince76** [comment]
je te laisse clore le point
