### ISSUE TITLE
Generic Type Manager - MAJ JUN20 : les commandes ne sont plus fonctionnelles depuis le dashboard (le retour d'info fonctionne)

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#17]

**Comment by fobsoft** [comment]
Next commit

**Comment by Nvince76** [comment]
Fonctionne de nouveau avec la dernière release
je clos le point

**Comment by Nvince76** [comment]
Je me relance en commençant par le début.
Ce point est réouvrir car ne refonctionne plus. Même comportement. Les retours d'état fonctionnent mais pas les commandes (depuis la tuile du GTM sur le dashboard)
