### ISSUE TITLE
UPDATE 21 JUIN : Le déclencheur (ou les actions) des taches ne sont plus fonctionnelles

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#19]
Test plusieurs fois et de diverse façon, mais le déclencheur (ou les actions) des taches ne sont plus fonctionnelles

**Comment by fobsoft** [comment]
Next commit 2022-06-22 20:15

**Comment by Nvince76** [comment]
De nouveau opérationnel 

Merci
