### ISSUE TITLE
Generic Type Manager - Slider a 0

### ISSUE THREAD

**Issue by fobsoft** [fobsoft/jeedom-plugins-documentation#2]
Action sur le slider d’intensité fonctionne bien, sauf le 0% qu’il n’accepte pas

**Comment by fobsoft** [comment]
Action sur le slider d’intensité fonctionne bien, sauf le 0% qu’il n’accepte pas

**Comment by fobsoft** [comment]
Encore une fois, si cela ne fonctionne toujours pas après les modifications peux-tu m'envoyer le log

**Comment by fobsoft** [comment]
Est-ce toujours d'actualité ?

**Comment by Nvince76** [comment]
yes, imppec
