### ISSUE TITLE
ADVANCED SCENARIO - QUESTIONS/REPONSES

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#23]
Je ne sais pas s'il s'agit du meilleur moyen mais j'ouvre ce fil pour poser mes questions au fur et à mesure de l'utilisation du plugin et éviter ainsi de mélanger avec les réelles issues

**Comment by Nvince76** [comment]
QUESTION 1 : 

Je viens de créer un scénario basique pour parcourir l'ensemble de mes objets sous 'MAISON' et afficher les équipement 'ROOM MANAGER' (voir ci-dessous).

![image](https://user-images.githubusercontent.com/44101114/175815579-39434478-9b03-40d0-bb58-b7a6d47a8416.png)

je n'ai pas l'impression qu'il parcoure tous les noeuds (à la vue de la log). Mon 'ROOM MANAGER du [Salon] (unique actuellement car sera cloné une fois au point)

[scenario107.log](https://github.com/fobsoft/jeedom-plugins-documentation/files/8986673/scenario107.log)

Coté LOG, j'ai beaucoup de mal à m'y retrouver. Y a t'il un moyen de n'afficher uniquement ce que je demande dans le scénario via le bloc LOG?

ci dessous l'arborescence de mon jeedom (il y a du monde et , rappel, je suis en pleine réorganisation)

![image](https://user-images.githubusercontent.com/44101114/175815757-08d0493a-fa2f-4cff-9347-48db977b5420.png)

![image](https://user-images.githubusercontent.com/44101114/175815788-f8ee2f3b-3cce-4062-a48c-aae2110588cc.png)

![image](https://user-images.githubusercontent.com/44101114/175815829-17bcd543-3840-4d38-b12d-fbf34ccc21d2.png)

![image](https://user-images.githubusercontent.com/44101114/175815864-585957b2-18ec-44b6-b5d8-58d9d7102bba.png)

**Comment by Nvince76** [comment]
Bonjour fobsoft, bon oubli l'aspect log, j'étais en avancé....c'est plus clair en passant en mode 'défaut'.

Par contre, j'ai beau retester, pour moi la boucle 'pour chaque' ne passe pas partout

**Comment by fobsoft** [comment]
Envoi moi le log avancée je veux voir ce qu'il sort de la recherche pour
savoir si c'est au niveau du array cree ou au niveau de la boucle. Je
travail justement sur les logs puisquil y a un bug dadans, mais le avancer
est effectivement plus pour de déboguage.

**Comment by Nvince76** [comment]
hello Fobsoft, tu as le log un peu plus haut, laisse moi savoir si tu as besoin de plus

**Comment by fobsoft** [comment]
oups j'avais pas vu, parfait

**Comment by fobsoft** [comment]
Enfait, il n'y a pas le debut du scenario dans la log, et je vois que celui-ci a 500 lignes exactement, est-ce que tu aurais une limitation ?

**Comment by Nvince76** [comment]
ah! Pas de limitation à ma connaissance. Il est vrai que j'en arrivais à la même observation (manque le début du log)
je vais regarder, je ne savais que l'on pouvait limiter la taille du log

**Comment by Nvince76** [comment]
bien vu +1
je refait un test

**Comment by Nvince76** [comment]
Impeccable
Merci
