### ISSUE TITLE
ADVANCED SCENARIO : time_op n'est pas correctement évalué (envoie -1)

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#28]
![image](https://user-images.githubusercontent.com/44101114/175837224-54be9385-ea9b-4471-b94b-afec2a74af06.png)

![image](https://user-images.githubusercontent.com/44101114/175837248-33835071-d81c-47d6-a1ba-d38521aecd9d.png)

**Comment by fobsoft** [comment]
commit du 2022-06-28

**Comment by Nvince76** [comment]
Merci Fobsoft, 
Pas encore reçu
L'as tu déjà poussé? je vais l'attendre pour poursuivre mon scénario

merci encore

**Comment by fobsoft** [comment]
c'etait dans la derniere version, j'avais juste oublier de commenter l'issue


Le mer. 29 juin 2022, à 15 h 27, Nvince76 ***@***.***> a
écrit :
