### ISSUE TITLE
Generic Type Manager - Clique sur ampoule éteinte

### ISSUE THREAD

**Issue by fobsoft** [fobsoft/jeedom-plugins-documentation#3]
Action sur l’icone de l’ampoule fonctionne uniquement sur l’allumage. A noter que l’intensité passe par 100% avant de redescendre sur sa valeur par défaut.

**Comment by fobsoft** [comment]
L'équipement n'a pas accès à la valeur par default, je vais donc tenter de changer le code puisque présentement je n'utilise que le slider lorsque disponible donc slider 100 lorsque l'ampoule est a 0 et vice versa. Peut-être que si la commande on  et off serait utilisé, sa serait le défault du GTM qui serait prit en charge.

**Comment by Nvince76** [comment]
ok et encore merci
"Présentement", tu es du Canada?

**Comment by fobsoft** [comment]
Oui effectivement
