### ISSUE TITLE
ADVANCED SCENARIO : LOG non fonctionnel?

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#30]
Bonjour Fobsoft, en voulant tester simplement time_op, je m'aperçoit que le bloc LOG n'est plus traité dans le log du scénario

![image](https://user-images.githubusercontent.com/44101114/176663051-04362e21-30fc-4633-bae5-cf5c513a4d7c.png)

![image](https://user-images.githubusercontent.com/44101114/176663178-ffcdcbee-7703-45fc-8919-e5464e514f82.png)

**Comment by fobsoft** [comment]
Je vais regarder, si tu veux poursuivre tes tests, tu peux essayé avec une
seul branche, c'est peux être le multiple branche qui a un problème.

**Comment by fobsoft** [comment]
Réessaie avec la prochaine version, si non fonctionnel envoi moi les logs avancé.

P.S. Je vais devoir révisé la création des logs de chaque type de noeud après les dernières modif. Donc sa risque de me prendre quelque jours.

**Comment by Nvince76** [comment]
hello, ne semble pas fonctionner avec la dernière version.
Prend ton temps surtout, ne te mets pas la pression.

![image](https://user-images.githubusercontent.com/44101114/176763471-dfc051a4-5c16-476a-8544-a6c727727a78.png)

**Comment by Nvince76** [comment]
![image](https://user-images.githubusercontent.com/44101114/176763673-8bc8d556-4491-42b2-bf6a-73a037a75a51.png)

**Comment by Nvince76** [comment]
[scenario109.log](https://github.com/fobsoft/jeedom-plugins-documentation/files/9022931/scenario109.log)

**Comment by Nvince76** [comment]
Je trouve log avancé un peu vide? non?

Bon courage et bon troubleshooting

**Comment by fobsoft** [comment]
si jamais tu as deux secondes configure le log à défaut au lieu de temps
réel pour voir quel sera la différence dans le log parce qu'effectivement
il est beaucoup trop cour

Le jeu. 30 juin 2022, à 15 h 45, Nvince76 ***@***.***> a
écrit :

**Comment by fobsoft** [comment]
Ah, j'avais pas les yeux en face des troues.... tu n'a pas de bloc
"Début".... tu dois l'avoir supprimé. Mais c'est le block de départ lors de
test. Donc il n'exécute rien. Je vais ouvrir un issue pour éviter la
suppression de celui-ci

Le ven. 1 juill. 2022, à 08 h 23, Francis Lemire ***@***.***> a
écrit :

**Comment by Nvince76** [comment]
Non pas sûr, en fait il est bien présent, simplement pas pris dans la copie
d'écran. Je ne le supprime jamais, je suis tes conseils 😉

**Comment by fobsoft** [comment]
K, mais est-ce qu;il y a un lien entre ce block et les block log ?

Le ven. 1 juill. 2022, à 11 h 36, Nvince76 ***@***.***> a
écrit :

> Non pas sûr, en fait il est bien présent, simplement pas pris dans la copie
> d'écran. Je ne le supprime jamais, je suis tes conseils 😉
>

**Comment by Nvince76** [comment]
non, il faut?

**Comment by Nvince76** [comment]
je teste

**Comment by Nvince76** [comment]
En connectant le bloc début, le log est plus complet en effet.

![image](https://user-images.githubusercontent.com/44101114/176973137-a0aadab2-1d7a-424a-a1ab-6ef44efdf507.png)

Mais la commande, bien que traitée, ne semblent pas être prise en compte par le GTM.


[scenario109 (1).log](https://github.com/fobsoft/jeedom-plugins-documentation/files/9031851/scenario109.1.log)

je vais essayer en envoyant la commande directement sur l'actionneur (volet)

**Comment by Nvince76** [comment]
je te remets le LOG, je t'avoue, des choses m'échape.
En passant en direct (bypassant le GTM), la commande fonctionne mais avec 20 min de décalage???
Fermeture du volet à 1% à 00hr40 et réouverture à 75% à 00hr42

![image](https://user-images.githubusercontent.com/44101114/176975166-bfbaff6d-083e-4670-8fb0-48b5e586ce64.png)
[scenario109 (2).log](https://github.com/fobsoft/jeedom-plugins-documentation/files/9031920/scenario109.2.log)

**Comment by fobsoft** [comment]
Je regarderais le log pour ce qui est du décalage. Oui il faut lier le
block début,  tu peux donc avoir pour le meme scenarion plusieur flow
d'entre un flow pour tester, x flow pour chaque programmation et x flow
pour chaque trigger.

**Comment by fobsoft** [comment]
Après analyse du log je constate qu'il y avait des erreurs
 - dans la gestion du résultat du if, malgré la condition qui était
fausse il exécutait le then au lieu du else .
 - Le time perdait c'est zéro, j'ai corriger mais puisque 0090 par exemple
n'est pas numérique, l'expression devra etre "0009" == "0011"

Présentement je vois que c'est une execution au minute, mais j'imagine
qu'au final tu auras deux block de programmation, l'une pour
l'heure d'ouverture et l'autre de fermeture ?

Je commit mes changements à l'instant, pour ton info je suis rendu à 80%
environ de la prog de gestion pour la creation de nouveau type générique.


Le ven. 1 juill. 2022, à 18 h 58, Francis Lemire ***@***.***> a
écrit :

**Comment by Nvince76** [comment]
Salut Fobsoft, 

Oui il y aura bien un bloc pour ouverture et un pour la fermeture.
Je viens de tester l'update, cela fonctionne bien pour le LOG et il n'y a plus de décalage.
Par contre, j'envoie directement la commande de sortie sur mes volet. si je passe par le GTM, cela ne fonctionne toujours pas (note : je ne pense pas que cela vienne de la configuration du GTM car cela fonctionnait il y a quelques jours et je n'y ai pas retouché depuis.)

En tous les cas, merci, cela progresse bien

**Comment by Nvince76** [comment]
Bon finalement, c'est la commande du GTM qui ne fonctionne plus (sur le dashboard), comme si un de tes correctifs passé n'a pas été répliqué (j'ai déjà rencontré ce problème et tu l'avais corrigé)

**Comment by fobsoft** [comment]
Es-tu en mesure de m'envoyer le log généré lorsque tu actionne la commande
que ce soit pas le scénario ou directement sur le dashboard ?


Le dim. 3 juill. 2022, à 11 h 05, Nvince76 ***@***.***> a
écrit :

**Comment by Nvince76** [comment]
[Action depuis le dashboard.log](https://github.com/fobsoft/jeedom-plugins-documentation/files/9035169/Action.depuis.le.dashboard.log)

**Comment by fobsoft** [comment]
nouvelle version

Le dim. 3 juill. 2022, à 12 h 50, Nvince76 ***@***.***> a
écrit :

**Comment by Nvince76** [comment]
[plugin783.log](https://github.com/fobsoft/jeedom-plugins-documentation/files/9035195/plugin783.log)


Volet déclenché par le scénario à 18h55, 18h56, 18h57
![image](https://user-images.githubusercontent.com/44101114/177050168-13bab11b-3f56-4bdc-a88e-4038d90913a2.png)

[Advanced Scenario.log](https://github.com/fobsoft/jeedom-plugins-documentation/files/9035196/Advanced.Scenario.log)

**Comment by Nvince76** [comment]
super, tout semble fonctionner

**Comment by Nvince76** [comment]
je te laisse fermer le request ;)

**Comment by fobsoft** [comment]
Haha, thanks!

**Comment by fobsoft** [comment]
Le meilleur moyen de récupérer ce block serait de créer un nouveau scénario

Le ven. 1 juill. 2022, à 08 h 28, Francis Lemire ***@***.***> a
écrit :
