### ISSUE TITLE
Advanced Scenario :  " Élément liés à l’exécution du scénario" (Trigger, TriggerObject, …) ne sont plus accessibles?

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#31]
Citation
si ton équipement mode sera dans le même objet, tu pourrais utilisé le tag triggerObject et ne pas envoyer le paramètre object

je n’arrive pas à utiliser les " Élément liés à l’exécution du scénario" (Trigger, TriggerObject, …)

Je voulais suivre ta remarque, plusieurs résumés de mon GTM peuvent appeler un même Advanced Scenario générique qui s’appuierait sur l’objet contenant le GTM qui l’aura trigged.
Sachant que ce GTM sera cloné, si je peux m’éviter de saisir pour chaque GTM et chaque appel du scénario un tag de passage… ce serait trop bien… sachant qu’à postériori je partirais sur un advanced scénario générique pour chaque organe commandé (Lumière, Volet, Prise, Chauffage)

![image](https://user-images.githubusercontent.com/44101114/177426274-4f7d5eba-1306-44dc-adb7-d5691551a573.png)
[scenario108.log](https://github.com/fobsoft/jeedom-plugins-documentation/files/9049984/scenario108.log)

![image](https://user-images.githubusercontent.com/44101114/177426415-d758e446-93e3-4233-a266-798f9e2c6c8c.png)

**Comment by Nvince76** [comment]
j'arrive à récupérer les tags passés mais toujours pas les éléments liés à l'exécution du scénario

**Comment by fobsoft** [comment]
Que veux tu dire par élément ?

**Comment by Nvince76** [comment]
![image](https://user-images.githubusercontent.com/44101114/178093279-969698fb-869f-4200-bb39-463c527c9d0b.png)

**Comment by fobsoft** [comment]
Ok, peux-tu me donner le log généré ?

Le sam. 9 juill. 2022, à 01 h 41, Nvince76 ***@***.***> a
écrit :

**Comment by Nvince76** [comment]
exemple : impossible de récupérer le #triggerObject# ou les autres

Merci de ton aide, il ne me reste plus grand chose pour boucler la gestion complète de mes volets via le GTM et Advanced scenario.
Une fois cette partie boucler, ça va rouler tout seul pour mes lumière, chauffage et autres organe

**Comment by Nvince76** [comment]
ok, je te recrée un scénario pour exemple (pas dans l'immédiat car il est 7h44 ici, la journée va commencer et toi, il serait temps d'aller te coucher ;)

Je te fais cela dans la soirée et tu l'auras en fin d'après midi

**Comment by fobsoft** [comment]
Pas de problème.

Le sam. 9 juill. 2022, à 01 h 45, Nvince76 ***@***.***> a
écrit :

**Comment by Nvince76** [comment]
bon, j'ai pris un peu de temps pour te le faire, si j'ai le correctif j'avancerais sur ma conf ce soir (mais pas d'urgence, prends ton temps)

[scenario110.log](https://github.com/fobsoft/jeedom-plugins-documentation/files/9075952/scenario110.log)

![image](https://user-images.githubusercontent.com/44101114/178093679-5970579c-d8c3-4a63-a31a-67af4c3d1de4.png)


scenario activé par le GTM en simulant un choc

![image](https://user-images.githubusercontent.com/44101114/178093709-84fafc41-af32-471f-901f-63dd044277fc.png)

**Comment by Nvince76** [comment]
autre prob, mais au passage saurais tu pourquoi ma tache basique ne se déclenche pas?
![image](https://user-images.githubusercontent.com/44101114/178093803-97756397-bfce-4661-bb59-1def3c51aa33.png)

pourque mon volet s'active je suis obligé de mettre un déclenchement par programmation dans l'advanced scenario, ce qui me fait perdre l'aspect générique de ce dernier. alors que si déclenché par le GTM aux heures définies, le scénario récupéreré le #triggerobject# du GTM appelant

**Comment by fobsoft** [comment]
#triggerObject#, change pour tag(#triggerObject#). Je modifirait le code
pour que cest tag sois accessible sans la fonction mais presentement elles
ne sont accessible que par la fonction commme si c'est toi qui les avaient
créé

Le sam. 9 juill. 2022, à 02 h 03, Nvince76 ***@***.***> a
écrit :

**Comment by Nvince76** [comment]
je viens de voir la liste de base renvoyée..
![image](https://user-images.githubusercontent.com/44101114/178093949-33164518-5f28-4e0a-9e87-c99f41956ce4.png)

**Comment by fobsoft** [comment]
Et dans l'appel du scénario dans le GTM, efface le tag puisqu'il est
généré automatiquement

Le sam. 9 juill. 2022, à 02 h 06, Francis Lemire ***@***.***> a
écrit :

**Comment by fobsoft** [comment]
Pour ce qui est du déclencheur, il n'y a que  le changement d'une valeur
d'une commande qui est prit en charge puisque c'est le listener qui est
utilisé. Par contre il serait intéressant d'avoir une programmation comme
déclencheur, j'ouvrirai un billet


Le sam. 9 juill. 2022, à 02 h 07, Francis Lemire ***@***.***> a
écrit :

**Comment by Nvince76** [comment]
essaye de suite
[scenario110 (2).log](https://github.com/fobsoft/jeedom-plugins-documentation/files/9075956/scenario110.2.log)

Ne fonctionne pas 

Dans le GTM, il n'a pas le même nom donc ne devrait pas poser de problème? mais par précaution, je l'ai supprimé

**Comment by Nvince76** [comment]
oui, c'était ma compréhension initiale, d'où la création d'un HEARTBEAT en résumé (pulse de 30 sec généré toute les min) mais je retombe sur le problème du déclencheur.
Oui une programmation en déclencheur serait un gros plus +1+1+1

**Comment by Nvince76** [comment]
je dois te laisser à plus tard, bonne nuit

**Comment by fobsoft** [comment]
Next commit

**Comment by Nvince76** [comment]
Hate
Je reprends mon GTM et scénario ce soir (heure française)

**Comment by Nvince76** [comment]
la liste est bien complète
grand merci

![image](https://user-images.githubusercontent.com/44101114/179370077-ba101bbd-c998-4348-bbfe-62f5c663dc87.png)

**Comment by Nvince76** [comment]
il y a encore un comportement étrange avec les log mais je ferme celui-ci et en ouvre un autre.
Ce n'est pas urgent pour les log, j'ai trouvé une alternative
