### ISSUE TITLE
Advanced Scenario : La désactivation d'un bloc ne fonctionne pas (plus?)

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#32]
![image](https://user-images.githubusercontent.com/44101114/177426783-ea67c9f3-f8aa-416d-994a-f623e0af8ea1.png)

**Comment by fobsoft** [comment]
Non effectivement, n'a jamais encore fonctionner. A venir

**Comment by fobsoft** [comment]
Next commit

**Comment by Nvince76** [comment]
Opérationnel

Merci
