### ISSUE TITLE
Juste un log des changes de tes updates. Je les charge mais ne sais pas ce qui a été amélioré ou corrigé

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#36]

**Comment by fobsoft** [comment]
En fait lors qu'il n'y a pas d'issue qui passe à tester c'est plus du général, le dernier c'était un problème de git, je semble avoir eu une perte de modification. En fds j'était en camping et je n'ai pas travailler à partir du même répertoire et il ne semble pas avoir apprécié. Et l'autre modif ce sont les logs générés lorsqu'il  y a des appel dans des appel

**Comment by Nvince76** [comment]
OK, merci de la précision.
Je guetterai les points à tester.
Bon séjour

**Comment by Nvince76** [comment]
Hello Fobsoft, 

Juste pour t'informer, je viens de pousser un de tes derniers update (je ne sais plus si c'est le GTM ou Advanced Scenario), ç a fait planter direct mon jeedom, plus d'accès. Je restaure ma VM.
Je crois, de mémoire que l'on avait déjà eu le cas il y a quelques mois, mais ne me souviens plus de la résolution

**Comment by Nvince76** [comment]
Bon, je viens de repasser les deux, c'est bien Advanced Scenario qui fait planter

**Comment by fobsoft** [comment]
Ok, je testerais sur ma partition beta ce soir pour trouver d'ou viens le
problème. Je soupçonne qu'il y a peut-être quelque chose en lien avec la
maintenance des type générique qui n'a pas encore été poussée.

Le dim. 10 juill. 2022 14 h 02, Nvince76 ***@***.***> a
écrit :

**Comment by fobsoft** [comment]
La gestion des type générique a été poussé dans la prochaine version, ce probleme devrai donc être résolut par la même occasion

**Comment by Nvince76** [comment]
Je viens d'updater les deux plugin, pas de plantage. Je vais refaire un tour et tester le tout

Merci
