### ISSUE TITLE
ADVANCED SCENARIO : Anomalie lors de l'utilisation du bloc Départ seul

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#39]
Ca continue de progresser de mon coté. Mais de nouveau bloqué.
Je  pense que mes problèmes de log sont liés à l'utilisation d'un scénario avec uniquement un bloc 'Départ' comme déclencheur.

En fait lorsqu'un scénario (Advanced) est uniquement trigged par le GTM, c'est à dire qu'il n'a qu'un bloc 'Départ' en déclencheur, le scénario est bien déclenché, mais impossible de disposer des tags du plugin (ex : triggerObject) et pas de Log...

![image](https://user-images.githubusercontent.com/44101114/179374853-632e4d63-f7c5-4e62-8752-d0aca0880841.png)

![image](https://user-images.githubusercontent.com/44101114/179374859-c601cb40-838a-44f6-b6d7-73735b66f57f.png)

[plugin783 (2).log](https://github.com/fobsoft/jeedom-plugins-documentation/files/9126773/plugin783.2.log)

Si j'ajoute un déclencheur, tout y est et fonctionne... sauf que cela m'empêche de rendre le scénario générique.
Je tiens vraiment a y arriver car, je vais avoir environ 18 GTM ROOM MANAGER, et 7 résumés vont potentiellement appeler ce scénario (volet dans le cas présent, mais il y en aura un pour les lumière, un pour le chauffage, un pour les prises...)

Exemple en ajoutant un déclencheur sur le résumé 'CHOC'

![image](https://user-images.githubusercontent.com/44101114/179375009-eac76b09-9eed-4ccf-a743-fb6b83e644e0.png)

[scenario110.log](https://github.com/fobsoft/jeedom-plugins-documentation/files/9126782/scenario110.log)

**Comment by fobsoft** [comment]
J'ai pas eu le temps de regarder les logs que tu m'as envoyé, mais le but
est que le premier scenario en attachement soit fonctionnel. D'autant plus
que dans le deuxième sa ne semble pas être un déclencheur qui a été ajouté.
Les noeuds qui sont utilisé comme déclencheur se trouve sous le groupe
trigger. Comme les scénario, cela peut être une trigger, une programmation
ou la changement de valeur d'une commande. Tu peux valider ce qui déclenche
le scénario si tu ce scénario dans l'outil de scenario de jeedom. Mon
camping fini ce lundi, je devrais être plus reactif après.

Le sam. 16 juill. 2022 19 h 32, Nvince76 ***@***.***> a
écrit :

**Comment by Nvince76** [comment]
Pas de souci, au contraire, profite de tes vacances.
Moi elles commenceront jeudi soir mais ne pars qu'à partir du 30.
Profites bien
Ici c'est la canicule
Il fait exceptionnellement 38°c

**Comment by fobsoft** [comment]
Lorsque tu fais time / tag(....

Le chiffre de ta division ce trouve dans quel commande exactement ?

Le dim. 17 juill. 2022, à 10 h 09, Nvince76 ***@***.***> a
écrit :

> Pas de souci, au contraire, profite de tes vacances.
> Moi elles commenceront jeudi soir mais ne pars qu'à partir du 30.
> Profites bien
> Ici c'est la canicule
> Il fait exceptionnellement 38°c
>

**Comment by fobsoft** [comment]
Dans plugin783.log, je vois l'execution du scenario a la ligne [2022-07-17
01:20:15][DEBUG]. Mais je constate qu'il n'y a pas de trigger envoyé, c'est
sûrement cela le problème. J'avais travaillé juste avec le mode à date, je
regarde cela.

Le dim. 17 juill. 2022, à 10 h 09, Nvince76 ***@***.***> a
écrit :

> Pas de souci, au contraire, profite de tes vacances.
> Moi elles commenceront jeudi soir mais ne pars qu'à partir du 30.
> Profites bien
> Ici c'est la canicule
> Il fait exceptionnellement 38°c
>

**Comment by fobsoft** [comment]
Next commit

**Comment by Nvince76** [comment]
le #time# / tag(triger...  était simplement pour voir le message avec l'heure et l'objet (ici [salon])
afin de m'assurer que le scénario était bien trigged et que je récupérais bien le tag Object

et pour la bonne nouvelle ton dernier update a solutionné le problème
Un grand merci, ne reste plus qu'à poursuivre de mon coté

encore un grand merci

**Comment by Nvince76** [comment]
je clos ce point

**Comment by Nvince76** [comment]
Hello Fobsoft

Bon ça progresse chez moi.
Je suis retombé sur un problème que tu avais solutionné avec les time_op et
les format de date.
J'ai un cas par exemple ou il vérifie 048 à 48 et me donne une condition
fausse.
Ainsi que des délai observés de plusieurs minutes avant exécution (exemple
la fermeture des volet à 00h48...)

Merci encore et bonne fin de vacances

**Comment by fobsoft** [comment]
Dans la prochaine version j'ai fait des correctif au log, si tu as toujours
un problème avec  time_op envoit moi le log

Le mer. 20 juill. 2022, à 07 h 52, Francis Lemire ***@***.***> a
écrit :

> Petite question hors propos pour être certain que je n'effacera pas
> quelque chose que tu aurais déjà configuré. Est-ce que tu as déjà créé de
> nouveau type générique ?
>
> Le mar. 19 juill. 2022, à 03 h 11, Nvince76 ***@***.***> a
> écrit :
>
>> Hello Fobsoft
>>
>> Bon ça progresse chez moi.
>> Je suis retombé sur un problème que tu avais solutionné avec les time_op
>> et
>> les format de date.
>> J'ai un cas par exemple ou il vérifie 048 à 48 et me donne une condition
>> fausse.
>> Ainsi que des délai observés de plusieurs minutes avant exécution (exemple
>> la fermeture des volet à 00h48...)
>>
>> Merci encore et bonne fin de vacances
>>

**Comment by Nvince76** [comment]
Ok merci Fobsoft, 
j'essaierai de m'y remettre ce soir, pas mal pris ces derniers jours avec le taff.

Je bloque sur un autre problème (enfin, ce n'est peut être pas un problème mais moi qui fait mal...), mais il me faut refaire des tests et documenter clairement mon observation. cela me donnera l'occasion de retester log et time_op.

mais ça progresse bien

**Comment by fobsoft** [comment]
Good, sache que ce matin, je m'appercoi qu'il y a encore des problèmes avec
les logs lorsqu'il y a des appels de fonction dans des paramètres de
fonction. Je travaille présentement dessus.

Le sam. 23 juill. 2022 04 h 36, Nvince76 ***@***.***> a
écrit :

**Comment by fobsoft** [comment]
Lorsque tu fais time / tag(....

Le chiffre de ta division ce trouve dans quel commande exactement ?

Le sam. 16 juill. 2022 19 h 32, Nvince76 ***@***.***> a
écrit :

**Comment by fobsoft** [comment]
Petite question hors propos pour être certain que je n'effacera pas quelque
chose que tu aurais déjà configuré. Est-ce que tu as déjà créé de nouveau
type générique ?

Le mar. 19 juill. 2022, à 03 h 11, Nvince76 ***@***.***> a
écrit :

> Hello Fobsoft
>
> Bon ça progresse chez moi.
> Je suis retombé sur un problème que tu avais solutionné avec les time_op et
> les format de date.
> J'ai un cas par exemple ou il vérifie 048 à 48 et me donne une condition
> fausse.
> Ainsi que des délai observés de plusieurs minutes avant exécution (exemple
> la fermeture des volet à 00h48...)
>
> Merci encore et bonne fin de vacances
>

**Comment by Nvince76** [comment]
Hello Fobsoft, 
welcome back.
je vais me replonger dedans car n'y ait pas mis les mains depuis.... presque 2 mois!!!
Il faut que je recolle les morceaux de là ou j'en étais dans mes tests..
Mais il faut que j'avance car je test directement en Prod, et donc j'ai 2 pièces avec une domotique bancal, mais c'est mon choix, je teste en grandeur réelle ;)

**Comment by Nvince76** [comment]
pour revenir à la dite division, ce n'est pas une division, je cherchais juste à afficher le message :
#time# / tag(Triggerobject, 0)
c'est à dire , en exemple;
22h28 / [Salon]
