### ISSUE TITLE
Generic Type Manager - Clique sur ampoule allumé

### ISSUE THREAD

**Issue by fobsoft** [fobsoft/jeedom-plugins-documentation#4]
Clique sur l'ampoule allumé n'éteint pas la lumière

**Comment by fobsoft** [comment]
Après les dernières modifications cela fonctionne chez moi, je rajoute donc  un log pour connaitre la configuration de la commande lors de l'action. Fait un test de ton cote et si cela ne fonctionne pas, envoi moi le log génére, je  vais pouvoir analyser ta config

**Comment by Nvince76** [comment]
Cela fonctionne à présent
+1
