### ISSUE TITLE
Generic Type Manager - Exécution des modes

### ISSUE THREAD

**Issue by fobsoft** [fobsoft/jeedom-plugins-documentation#6]
La sélection des modes ne fonctionne plus. Comme si ces derniers ne pouvaient fonctionner qu’uniquement au travers des conditions d’entrées (dont je n’ai pas besoin vu que l’action est manuelle). As tu une petite idée de ce qui coince?

**Comment by Nvince76** [comment]
[plugin706.log](https://github.com/fobsoft/jeedom-plugins-documentation/files/8808519/plugin706.log)

**Comment by Nvince76** [comment]
Log posté

Bien vu le suivi des request via GIT

**Comment by fobsoft** [comment]
Il y avait effectivement une conditionnel qui forçait la présence d'action pour l'exécution du mode, tient moi au courant si la modification à résolue le probleme

**Comment by Nvince76** [comment]
100% fonctionnel
Pas au début, mais c'était de mon coté, à modifier dans tous les sens pour vérifier que cela ne venait pas de ma conf... les modes fonctionnaient bien mais pas ma gestion de ces derniers.
Tout est rentré dans l'ordre

Merci
