### ISSUE TITLE
Generic Type Manager - Impossibilité de créer deux résumés avec le même Type

### ISSUE THREAD

**Issue by Nvince76** [fobsoft/jeedom-plugins-documentation#8]
Afin de permettre de ségréguer des lumières dans une pièce (mais peut être étendu à tous types de résumé), il serait intéressant de pouvoir créer plusieurs résumés de même type (ex : Lumières principale, Lumière d'ambiance, ...). Actuellement, la création de deux résumés de même type n'affiche que le premier créé.

**Comment by fobsoft** [comment]
Je viens  de  faire un test et j'ai réussi à avoir deux résumer light state.  Tente d'en créer un premier, puis sauvegarde tes changement. Ensuite crée ton deuxième. Mais j'avoue que la programmation n'a pas été faite pour cela alors tient moi au courrant de ce que cela donne.

**Comment by Nvince76** [comment]
testé de nouveau et même constat. J'arrive à le créer mais il n'apparait toujours pas sur le dashboard.
De ton coté, tu arrives à voir le deuxième résumé sur ta tuile? et interagir avec?
Désolé de te faire perdre du temps sur cela

**Comment by fobsoft** [comment]
Ah k, le probleme  ce situ sur le dashbord.... je me suis mémé pas rendu la, j'était sure que le probleme se trouvait dans la  configuration, je vais regarder. surement un array que je  rempli  et un écrase l'autre. Tu ne me dérange pas, le plugin est un peu chère mais c'est dans l'optique de donné un bon support.

**Comment by fobsoft** [comment]
Mise a jour du 2022/06/05

**Comment by fobsoft** [comment]
Laisse moi savoir si le  double résumé fonction

**Comment by Nvince76** [comment]
ok ce point là fonctionne
nickel
