### ISSUE TITLE
Utilisation du flap

### ISSUE THREAD

**Issue by fobsoft** [fobsoft/jeedom-plugins-documentation#9]
Envoit moi un screen shoot de ta config de virtuel, je  vais reproduire chez moi pour voir ou sa cloche

**Comment by Nvince76** [comment]
![image](https://user-images.githubusercontent.com/44101114/172228801-1daa7faf-119e-42f2-9499-59221d2cfe59.png)

![image](https://user-images.githubusercontent.com/44101114/172228927-f25d6151-7cc0-44a0-aa6e-d5b3abf6dbc7.png)

![image](https://user-images.githubusercontent.com/44101114/172229306-b626a3d5-afd6-474d-b13a-02c99d485e5e.png)

Voici pour mon virtuel (adossé à un scénario, qui fonctionne très bien depuis 3 ans)

**Comment by Nvince76** [comment]
![image](https://user-images.githubusercontent.com/44101114/172229458-8f4bf6b8-0156-4557-bc0a-94879c49d897.png)

![image](https://user-images.githubusercontent.com/44101114/172229616-4bc181ff-cc61-49a2-a234-9fbbdeea82a1.png)

**Comment by Nvince76** [comment]
En précision, la modification de la consigne d'ouverture de mon volet remonte bien sur mon GTM
Ce qui ne fonctionne pas est la modification de la consigne de position du volet depuis le GTM qui n'est pas appliqué sur mon virtuel.

Laisse moi savoir s'il te manque autre chose pour débugger
je vais t'envoyer le log du GTM

**Comment by Nvince76** [comment]
[plugin715.log](https://github.com/fobsoft/jeedom-plugins-documentation/files/8846962/plugin715.log)

Les deux premières commandes ont été effectué depuis le virtuel, et le deux dernières commandes ont été effectuées depuis le GTM

**Comment by Nvince76** [comment]
Ne perd pas trop de temps avec cet issue, je viens de réussir à le faire fonctionner. En fait, l'info 'Consigne de Position' n'avait pas conserver son type générique (Flap_State)...
Fonctionne bien, il faut maintenant que j'adapte à mon échelle -5% à+100%

**Comment by fobsoft** [comment]
Je crois que pour l'échelle, il serait préférable de pouvoir spécifier un min/max au GTM. Comme chez mon je n'ai que des lumière, par défaut dans le code c'est de 0 a 99. Jamais je n'aurais penser qu'il pouvais avoir un autre range. Du coup il n'y a pas de flexibilité à ce niveau... Je vais donc ajouter cela, et sa devrai régler ton problème

**Comment by fobsoft** [comment]
Ajout d'une configuration de valeur minimum et maximum dans le sommaire. Ainsi lors d'échange avec une commande, une règle de 3 est appliqué pour calculer la valeur de la commande.

**Comment by Nvince76** [comment]
Vu que c'est mon virtuel et code, je suis en train de le recoder pour le normaliser en 0-99%
Mais c'est bien vu, cela donnera de la flexibilité si l'on rencontre d'autre besoin de ce type

**Comment by fobsoft** [comment]
C'est pour toi, la modification est dans la prochaine mise a jour

**Comment by Nvince76** [comment]
Merci ;)
Semble bien fonctionner
